### ISSUE TITLE
Unnecessary to Recreate ThreadPoolWork each time

### ISSUE THREAD

**Issue by smj389** [raftario/wae#1]
At the moment, spawn recreates the ThreadPoolWork every time around and then closes it in the callback.
Because the only difference in the behaviour of the callback for each work item depends on the context ptr, the same WorkItem could be used each time with a different context ptr. This WorkItem could be created lazily or when the pool is created and used until the pool is closed.

**Comment by raftario** [comment]
I'm curious, what's the cost of creation of a work item ? Also, how would that work in the context of an executor running a large amount of tasks concurrently ?

**Comment by smj389** [comment]
A single WorkItem can run multiple times in parallel (potentially with different contexts pointers). SubmitThreadPoolWork is guaranteed to succeed, but CreateThreadPoolWorkItem is not because there is a memory used with each WorkItem.  So the design I have suggested is better for higher parallelism. I'll work on that design and submit a PR at some point.

**Comment by raftario** [comment]
What kind of design did you have in mind ? Using a task queue and and using a pointer to that or something a bit more involved ?

**Comment by smj389** [comment]
It's a lot simpler than that. We create the WorkPoolItem when the Pool is created or on demand and store the PTP_WORK in the ThreadPool object. We then reuse it everytime. On Demand requires us to use a OnceCell or something similar. And then we just keep using it. We can then use ThreadPool cleanup at the end.

**Comment by smj389** [comment]
I'll mock something up.

**Comment by raftario** [comment]
I get the general idea, I was referring to the way to pass the different runnable/handle pairs to the work callback since (afaik) the data pointer itself can't be changed once the work item has been created.

**Comment by smj389** [comment]
Sorry I seem to have a had a brain collapse. I was misremembering the API. I thought you could change the context ptr. In any case, the call to CloseThreadPoolWork can be omitted given you are using CloseThreadpoolCleanupGroup. Sorry for wasting time. I have submitted a PR on the other thing.

**Comment by raftario** [comment]
I'm still going to reopen this, using something like crossbeam's `SegQueue` and a single work item would avoid the extra context switch, prevent failures in the scheduling function and only allocate every so often instead of every time.

**Comment by smj389** [comment]
Yes, I can see that. Create three WorkItems - one for each priority (dynamically as first required) and then do SubmitThreadPoolWork each time it's necessary to schedule. The Callback then just loops around and takes the next item off the top of the Queue.

**Comment by raftario** [comment]
The discussed changes are implemented !
