### ISSUE TITLE
Copying Around TP_CALLBACK_ENVIRON

### ISSUE THREAD

**Issue by smj389** [raftario/wae#5]
I believe there should be a single copy of TP_CALLBACK_ENVIRON with only the pointer being copied around.

**Comment by raftario** [comment]
The copying was to make it possible to change the callback priority, but the design changes in #1 would change the way this needs to be implemented anyway. I was maybe thinking of storing pointers to three work items and theee contexts (one for each priority) and pick one based on the current handle's set priority. Any thoughts on that approach ?

**Comment by smj389** [comment]
Having three CallbackEnvironments would work - but I would create them on demand maybe. to avoid creating excess state.

**Comment by raftario** [comment]
You're right, they're not really useful since the work items would be created at initialisation.
